services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5020:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev

  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: backend
    depends_on:
      - db
      - redis
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      JWT_SECRET_KEY: z_f%#7x&0!n6uuamyca%y5swv1(9e=u=wu9s#wy(3f-k__k777
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    command: bash -c 'fastapi dev --host 0.0.0.0 --port 8000'
    volumes:
      - ./core:/usr/src/core

  celery_worker:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: celery_worker
    depends_on:
      - db
      - redis
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      JWT_SECRET_KEY: z_f%#7x&0!n6uuamyca%y5swv1(9e=u=wu9s#wy(3f-k__k777
      REDIS_URL: redis://redis:6379
    command: bash -c 'celery -A core.celery_conf worker --loglevel=info'
    volumes:
      - ./core:/usr/src/core
  celery_beat:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: celery_beat
    depends_on:
      - db
      - redis
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      JWT_SECRET_KEY: z_f%#7x&0!n6uuamyca%y5swv1(9e=u=wu9s#wy(3f-k__k777
      REDIS_URL: redis://redis:6379
    command: bash -c 'celery -A core.celery_conf beat --loglevel=info'
    volumes:
      - ./core:/usr/src/core

  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379/3', '--port=5555' ]
    ports:
      - 5555:5555
    depends_on:
      - redis

volumes:
  smtp4dev-data: